name: CI ~ Validate Code Style

on: [push]

jobs:
  build:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm install

      - name: Running Prettier and Eslint
        run: npm run format:check && npm run lint
